Feature branch
Haywhizzz/Restaurant-Page pull request #2
Opened 2021-01-25 08:21 UTC by Haywhizzz

In this project I have

- I set up Webpack to manage the js files

- I put each page code in individual files that I called the index.js

- Added some basic styling with CSS

- Kept the HTML clean with only one div inside as required

2021-01-25 11:08 UTC, mikenath223 requested changes
### Hello @Haywhizzz 👋

**You've done pretty well here.**

However, we are a step from moving on.

- Please refer to comments on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2021-01-25 11:11 UTC, mikenath223 commented on package.json
> +  },
- [ ] Kindly add the neccessary start scripts:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

2021-01-25 11:18 UTC, mikenath223 commented on package.json
> +  },
- Also if the optional start script is used make sure to include the `web-dev-server` package.

2021-01-26 11:12 UTC, whiz25 requested changes
## Changes Required 🤞🏿 
You did well in this PR @Haywhizzz . Your README is professional and the app looks good However, the `scripts` section of the `pakage.json` files needs fixing. See my comment.


### Martin Afani

2021-01-26 11:12 UTC, whiz25 commented on package.json
> +    "dev": "webpack-dev-server --open"
- Please use the same commands as here:
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

2021-01-26 12:03 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 

Great job @team, thanks for making the required changes.

now you can merge, your project is approved.

## Happy Coding :tophat:

2021-01-28 07:21 UTC, merged